#
# this file provides configuration for Travis Continuous Integration
#

language: php

dist: trusty

install: composer install
 
matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm

script: phpunit --coverage-text -c phpunit.xml

